Add function to clean up existing models
opensearch-project/demos pull request #73
Opened 2023-10-25 19:57 UTC by ortegaa32

### Description
Adds a function to clean up existing models after testing.

### Issues Resolved
Resolves #53 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-28 23:09 UTC, dtaivpp requested changes

2023-10-28 23:09 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  for state in MODEL_STATE:
Here for clearing model state, lets instead take each of the parameters and assign their values to None. that way if there are multiple tests that depend on this data structure they can simply re-populate it.

2023-10-29 20:09 UTC, ortegaa32 commented
Just made the relevant change

2023-10-30 18:29 UTC, dtaivpp requested changes
Looks good over all! Just address the few comments and we are good to merge.

2023-10-30 18:29 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  if delete_index_response:
For index response, we should check for `{'acknowledged': True}` here

2023-10-30 18:29 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  if delete_pipeline_response:
Here we also want to check for `{'acknowledged': True}`

2023-10-30 18:29 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  if delete_connector_response:
For deleting the connector we should look for result: deleted and failed: 0 in 

```json
{'_index': '.plugins-ml-connector', '_id': '63fKgYsBwPaemUsm3MGE', '_version': 2, 'result': 'deleted', '_shards': {'total': 1, 'successful': 1, 'failed': 0}, '_seq_no': 1, '_primary_term': 1}
```

2023-10-30 18:29 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  if delete_model_response:
We should check here for result: deleted and failed: 0

```json
{'_index': '.plugins-ml-model', '_id': '8HfLgYsBwPaemUsmvMFi', '_version': 5, 'result': 'deleted', '_shards': {'total': 1, 'successful': 1, 'failed': 0}, '_seq_no': 4, '_primary_term': 1}
```

2023-10-30 18:29 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +  if undeploy_model_response:
For this one we should check for stats: {<key1>: undeployed}

```json
{'sqGoQAqVQJGCzU6yLgTStg': {'stats': {'8HfLgYsBwPaemUsmvMFi': 'undeployed'}}}
```

2023-11-01 20:17 UTC, dtaivpp approved these changes
Looks great thanks!

2023-11-01 20:17 UTC, merged