add defaults to cluster_bootstrap.py
opensearch-project/demos pull request #75
Opened 2023-10-26 04:34 UTC by LucasWang750

### Description
add defaults to cluster_bootstrap.py

### Issues Resolved
Closes [#65]

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-26 04:34 UTC, LucasWang750 commented
Since dictionaries are mutable. There might've been a risk of default dict parameter being mutated so I used None instead.

2023-11-09 18:19 UTC, dtaivpp requested changes
Sorry that the issue was too vague and that it took me till now to get feedback in. Let me know if you have any questions!

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_cluster_settings(client: OpenSearch, cluster_setting=None) -> None:
Here can we remove the template parameters? We really just need to pull out the parts that may be variable. For this one I think they can all stay.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def init_index_template(client: MLClient, template_name = "nlp-template", template_data=None) -> None:
Here we can drop template data as I think template name may be the only variable. We may pull out index patterns as well. I'll leave that decision to you.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_model_group(client: MLClient, model_group_name="Cohere_Group", data=None) -> None:
Here I think the group name should be the only variable in here.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +        if data is None:
What we can do to make data a little more modular is we can make the model group name appear in the description with f-strings so each would have the right name if we ever changed the model group name.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_connector(client: MLClient, connector_name="Cohere Connector", connector_data=None) -> None:
Here we can remove the connector_data.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +            "name": "Cohere Connector",
We should probably be using the variable name here. Then in the description below we can use f-strings again to get the connector name to show correctly there.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_model(client: MLClient, model_data=None) -> None:
We can remove the model_data here and can instead just pull "name" out and have that be variable.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_ingestion_pipeline(client: MLClient, pipeline="cohere-ingest-pipeline", pipeline_data=None):
Here we can remove pipeline data. Again below in the description we can make it more modular by including our variable pipeline name in the description.

2023-11-09 18:19 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +def initialize_index(client: MLClient, index="cohere-index", index_data=None) -> None:
Here we can remove index_data and maybe we should lift the default pipeline as variable.

2023-11-28 01:56 UTC, closed without merging