Add methods for search pipeline endpoints
opensearch-project/demos pull request #97
Opened 2023-11-07 21:33 UTC by ortegaa32

### Description
Added method to perform request on `PUT /_search/pipeline/<id>` endpoint as well as `GET /_search/pipeline/<id>` endpoint

### Issues Resolved
Resolves #93 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-09 17:56 UTC, dtaivpp requested changes
2 small changes and all good!

2023-11-09 17:56 UTC, dtaivpp commented on demo/docbot/util.py
> +         url=_make_path("search", "pipeline", id)
Should this be `_search`?

2023-11-09 17:56 UTC, dtaivpp commented on demo/docbot/util.py
> +  def put_search_pipeline(self, id: str, body : dict) -> dict:
Small formatting can we put the : next to body?

2023-11-09 19:14 UTC, ortegaa32 commented
Just made the changes

2023-11-13 14:28 UTC, dtaivpp approved these changes
Looks great!

2023-11-13 14:28 UTC, merged