Implement function to initialize rag search pipeline
opensearch-project/demos pull request #98
Opened 2023-11-07 23:20 UTC by ortegaa32

### Description
Adds method to initialize the RAG search pipeline as well as making it the default for the `cohere-index`.

### Issues Resolved
Resolves #82 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-09 17:59 UTC, dtaivpp commented on demo/docbot/cluster_bootstrap.py
> +            "context_field_list": ["text"]
For context field list I think we are looking for our `content` filed here

2023-11-09 18:00 UTC, dtaivpp requested changes
One change and I think this will be good!

2023-11-09 19:14 UTC, ortegaa32 commented
Just made the relevant change

2023-11-13 14:32 UTC, dtaivpp approved these changes
Awesome! Thanks :D

2023-11-13 14:32 UTC, merged